ports:
  - port: 3333
    onOpen: open-preview

tasks:
  - init: |
      touch /tmp/.yarn-lock
      yarn install
      rm /tmp/.yarn-lock
 
  - init: sleep 1 && while [ -f /tmp/.yarn-lock ]; do sleep 1; done
    command: yarn dev

image:
  file: .gitpod.dockerfile
